---
- name: Nginx - Install Nginx
  apt:
    name: nginx
    state: installed
    update_cache: true

- name: Nginx - Change default config
  template: src=default.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx