---
# Document root
doc_root: /usr/share/nginx/html/wordpress/

# Wordpress database settings
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: wordpress

# Use for nginx config
server_hostname: wp-ansible.vagrant

